### ISSUE TITLE
Question about repository arrays

### ISSUE THREAD

**Issue by cyupa** [strongloop/loopback-authorization-extension#1]
Hi, 

I did a clone of this repo and did some adjustments to it but I haven't figured out why are some injected repositories declared as an array? Like down here:

https://github.com/strongloop/loopback-authorization-extension/blob/15726172d8788932f47eecb3ca486b3b04e6348d/src/repositories/role-permission.repository.ts#L41

Thanks for sharing this. 😃

**Comment by ckoliber** [comment]
Injecting a repository into a component is a little complicated,

You will define your custom repository, then you must add a tag to it for finding your repository in the component ( using `@bindUserRepository()` decorator, you add some tags to it)

And at the component level, your repository will be located using it's tags and `@injectUserRepository()` decorator

The result of this method is an array of matching items

https://github.com/strongloop/loopback-authorization-extension/blob/15726172d8788932f47eecb3ca486b3b04e6348d/src/keys.ts#L27-L39

You can find a complete example of component usage in [this link](https://github.com/koliberr136a1/loopback-authorization-example)

**Comment by cyupa** [comment]
Sure, I am aware of how dependency injection works, I just don't get it why in some cases it injects an array of repositories (and only uses the first one) and in other cases it's straight-forward and just uses a single repository instance.
Thanks for reaching out.

**Comment by ckoliber** [comment]
Because return type of inject decorator using a filter function is an array of items,
you can find more informations about `@inject`, [here](https://loopback.io/doc/en/lb4/Decorators_inject.html)

**Comment by cyupa** [comment]
Awesome. Thanks for your answer and for sharing this extension on GitHub.
